### ISSUE TITLE
Reserve PyPI project namespace / package namespaces

### ISSUE THREAD

**Issue by lhawthorn** [instructlab/community#126]
@tiran has offered to help with this effort, he writes:

Are you also going to publish the package to PyPI? If yes, then we have to have a conversation about the Python project name and toplevel package name. PyPI blocks cli for security reasons, because it's such a common name. I checked, the project names ilab and instructlab are unused on PyPI. They might be blocked, though. I suggest that one of the core maintainers creates an empty dummy project and uploads it to [test.pypi.org](http://test.pypi.org/) and [pypi.org](http://pypi.org/) to reserve the name.
Once we have the project name reserved, we should also rename the toplevel package name from cli and move the code into a src directory (e.g. git move cli src/instructlab). The src directory is important for testing. Right now our CI does not test the Python dist correctly.
If you have any questions or want assistance, feel free to ping me. I have plenty of experience with PyPI publishing and Python packaging.

Since the project owns [instructlab.io](http://instructlab.io/), it would make sense to reserve the PyPI name instructlab as well.

t's considered good practice to use the same name for the project name and top level package name. instruct-lab is not a valid Python identifier. PyPI normalizes instruct-lab to instruct_lab.

You can request to block instruct-lab on PyPI to prevent typo squatting attacks.

**Comment by jjasghar** [comment]
success!
