### ISSUE TITLE
Reevaluate Code of Conduct committee / reporting approach

### ISSUE THREAD

**Issue by lhawthorn** [instructlab/community#137]
Right now, our code of conduct reporting process specifies that our code of conduct committee members are:

@caradelia 
@joesepi 
@jberkus 

We should revisit this list and determine:

1. Is this the right list of people? For example, do we need more than 3 people? Should this be all intructlab/community maintainers (@lhawthorn thinks yes)
2. Can we get a more robust set of guidelines listed for how incident reports are handled?
3. Is the phrasing on the code of conduct page sufficient to explain how things should be escalated to CoC committee

**Comment by jjasghar** [comment]
Closed and a process is in place.
