### ISSUE TITLE
Documented RFC process?

### ISSUE THREAD

**Issue by jjasghar** [instructlab/community#211]
If we are going to create a "long-lived" conversation(s) in GitHub issues and mailing list(s), should we have a documented RFC process?

I remember doing it (successfully) in the Chef community like [this one](https://github.com/chef-boneyard/chef-rfc/blob/master/rfc061-hugs.md).

So maybe we create a GitHub Issue template with the outline or whatever so we can standardize on it? We should also create a path for submissions, acceptance, rejection, etc.

This was the [RFC process](https://github.com/chef-boneyard/chef-rfc/blob/master/rfc000-rfc-process.md) from which I think we can take real inspiration.

**Comment by lhawthorn** [comment]
We totally need this process. I am going to self-assign and if no one sees a PR on same by start of June, please rightly call me a cookie licker and nudge me to get moving.

**Comment by lhawthorn** [comment]
I am hereby calling myself a cookie licker and noting I will not get to this task until the week of 3 June 2024. If I am blocking someone else from working on this issue, please note it here and I will get out of the way!
