### ISSUE TITLE
Unable to edit the field for www.redhat.com while trying to sign up for slack workspace 

### ISSUE THREAD

**Issue by veniceofcode** [instructlab/community#215]
![Screenshot from 2024-04-25 12-32-20](https://github.com/instructlab/instructlab/assets/93591339/8443f35b-6df5-4902-aff0-fcd0a4b1188b)
![Screenshot from 2024-04-25 12-34-02](https://github.com/instructlab/instructlab/assets/93591339/8321b1f8-e8e8-43a8-92ee-b211399369f2)

**Comment by joesepi** [comment]
@veniceofcode - can we consider this resolved?

**Comment by veniceofcode** [comment]
@joesepi yes , i was able to sign up this morning , thanks a lot for the quick help.
