### ISSUE TITLE
Set up social channels for InstructLab

### ISSUE THREAD

**Issue by cybette** [instructlab/community#216]
Main channels:

- X/Twitter https://twitter.com/instructlab
- LinkedIn https://www.linkedin.com/company/instructlab/
- YouTube https://www.youtube.com/@InstructLab 

Coming soon:

- Mastodon https://mastodon.social/@InstructLab
- Bluesky https://bsky.app/profile/instructlab.bsky.social
- Reddit https://reddit.com/r/instructlab

**Comment by lhawthorn** [comment]
@cybette My plan is to list on our "collaboration page" the social media handles for X (Twitter), LinkedIn, and YouTube. Does that work for you?

**Comment by cybette** [comment]
@lhawthorn sure, I can add that when the page is ready!

**Comment by lhawthorn** [comment]
In progress PR at https://github.com/instructlab/community/pull/221

Feel free to review and merge PR if you are happy with what I have listed for social channels and the rest of the documentation looks good. Thank you!

**Comment by jimmysjolund** [comment]
Would a Mastodon account be in the plan?

**Comment by cybette** [comment]
@jimmysjolund [yes](https://mastodon.social/@InstructLab), although for launch/Summit we'll focus on the 3 Leslie mentioned

**Comment by lhawthorn** [comment]
@jjasghar suggested we get ourselves a Linktree, too, I have documented it in #272. There is no urgency on that issue, just mentioning it for the sake of being thorough.

I feel that this issue has been resolved now that we have secured all the channels listed herein.

Perhaps the only other outstanding item is to add Reddit, Bluesky, and Mastodon to our [Collaboration](https://github.com/instructlab/community/blob/main/Collaboration.md) page, even if just to note we are not active on e.g. Bluesky and Mastodon. We are active on Reddit and should most certainly have that info on the page. 

@cybette Would you like me to open a new issue for the above request?

**Comment by cybette** [comment]
Opened #296 and closing this.
