### ISSUE TITLE
Signs for booths/tables at conferences

### ISSUE THREAD

**Issue by lhawthorn** [instructlab/community#229]
We need a cool sign with a QR code that takes folks to the collaboration page in the community repo so they can easily sign up for mailing lists etc.

Should make sure template is in community repo.

For immediate needs for red hat summit, obtain 15 sign holders and print outs in color of signs.

Size table top sign for summit for 8.5 x 11 inches 

For repo also include sign sized for A4

**Comment by cybette** [comment]
![Instructlab_collab_QR](https://github.com/instructlab/community/assets/2913667/edf9f398-87af-4897-be56-2d2d44e68845)

**Comment by lhawthorn** [comment]
Oh your QR code is much better, I am using it instead!

**Comment by lhawthorn** [comment]
[InstructLab_CollabPage_Booth_Flyer-8.5x11.pdf](https://github.com/instructlab/community/files/15209155/InstructLab_CollabPage_Booth_Flyer-8.5x11.pdf)

[InstructLab_CollabPage_Booth_Flyer-A4.pdf](https://github.com/instructlab/community/files/15209158/InstructLab_CollabPage_Booth_Flyer-A4.pdf)
