### ISSUE TITLE
automatically open PR each week in community repo to capture community meeting agenda items

### ISSUE THREAD

**Issue by lhawthorn** [instructlab/community#258]
At time of writing, a subset of our [Community Maintainers](https://github.com/instructlab/community/blob/main/MAINTAINERS.md#community) are building the agenda for our weekly community meetings. 

It would be optimal to also collect agenda topics from the whole community and to do so on a more automated basis.

Proposal is to create a periodic GitHub action that would open a new issue in the Community repo each Tuesday at 15:00 UTC to solicit topics for the next week's meeting agenda.

See as a related example this script which runs automagically to update our Maintainers.md file.

Quoting @russellb: 
This is similarish, but what you need is a little simpler.
https://github.com/instructlab/community/blob/main/.github/workflows/periodic-maintainers-update.yml
that one runs every day, runs a script, and then creates a PR with the output if the scripts results in any changes.

**Comment by jjasghar** [comment]
This is still a good idea to make happen, we should revisit this as we start ramping up the community meetings again.
