### ISSUE TITLE
RFC: InstructLab regular communications - medium, timing, etc.

### ISSUE THREAD

**Issue by lhawthorn** [instructlab/community#261]
I believe we should provide regular summary communications about InstructLab for folks. Content to be featured should help folks learn more about project activities (e.g. latest releases and cool new features), ways to contribute, and - in my ideal universe - news the project maintainers find interesting from the world of all things open and AI.

We wish to provide project members and those interested in our approach to openly licensed models with useful things to read, not to be a content farm for the sake of 'driving engagement.' 

Non-goals:
* Create a newsletter or other vehicle we cannot regularly feed with content
* Duplicate other communication channels such as our email lists, etc. 

I presume one way to meet this goal would be to have an InstructLab blog where we could then repost the content to other channels. The nice thing about a blog is it allows for wider types of discourse on a variety of topics, including perhaps asking folks we respect in the AI space to share their overall thoughts with us and perhaps their opinions about what we are doing with InstructLab. 

Another plus in my view is that there is no specific deadline driven need to post; in other words, creating a "This Week in InstructLab" newsletter means we'd have to publish something weekly even if we didn't have much to say. 

We could, however, at least collect topics for and aim to have some sort of editorial calendar as the project evolves.

Specifically seeking feedback as part of this discussion:
* Do the community maintainers (and, in fact, all project maintainers) have time to sustain such an effort at this time? I believe the answer is an unequivocal "no, but it would sure be nice if someone wanted to help with this matter."
* How do we collect topics we think would be useful to address in article format so we do not lose sight of them whilst we do not have time to write them?
* Do we think a blog is a good idea vs. say a newsletter? Why or why not? What are people even using to subscribe to the Blogosphere these days? (RIP Google Reader, yes I am still sad for your demise.)

There is no urgency to this discussion, but I would like to hear from our community members what they would find most useful, and from our maintainers what they think would be a sustainable way to produce *useful* content.

**Comment by jimmysjolund** [comment]
First off, why is this discussion in Issues and not in Discussions? I think not every passerby or community member check all the issues, but noticing something in Discussions might be.

I think a blog is a good idea, for the reasons already mentioned. It doesn't put a pressure on "weekly" or other regular postings. It does need to be active though or people will stop checking the blog. (I'm not using any app to keep track of updates, either I go there manually or I get a notification through another media such as LinkedIn or Mastodon)

A blog is searchable in a better way than for instance a newsletter, I have many times tried find something and found what I needed in a blog post somewhere. I don't believe that will happen in another format. Blog posts will also be indexed by search engines, making it more accessible.

I also believe a blog might make it easier to get external people contributing, it's easier to write a blog post than to engage and get something included into a newsletter.

The backlog of potential topics is hard. What we have used in other communities is an editorial project on GitHub with a board showing Ideas, In writing, Published, etc. We just need to make sure the backlog of Ideas are filling up and is picked up into writing.

**Comment by spotzz** [comment]
I'm of two minds here, I definitely have a preference to things that are pushed to me ie emails, newsletters, etc., I do however like the searchability of a blog. If the newsletter could also be posted to the blog that would be ideal in my world:)

**Comment by wking** [comment]
Some weakly-held opinions; keep anything that sounds interesting and ignore the rest :)

> Content to be featured should help folks learn more about project activities (e.g. latest releases and cool new features)...

I'd expect release notes for this, and [we're doing that already][1].  Although maybe there's room to add a top-level paragraph picking out some highlights?  [The 0.15.0 release][2] looks like an unordered Git dump, which is cheap to produce, but hard to consume.  More effort in tuning the release notes might make it easier for new community members to identify the important bits and get excited.

> ... ways to contribute...

This also seems like something [we already do][3], and it's harder to fit into a periodic-release blog/newsletter publication cycle.  Unless there are calendar events like irregular meetups/conferences that need to be pushed out to the community, and we may not be that far along yet?

> ... in my ideal universe - news the project maintainers find interesting from the world of all things open and AI.

This kind of thing seems like a better fit for a newsletter/blog/periodic.  If folks have a win like "wow, I used this tooling to build `$COOL_THING`, and here's a summary and link to _my_ blog about it...", that would be very interesting.  But we already have [a users list][4] that includes "user feedback on project", so not sure we need something flashier than that mailing list until we get at least one message to the mailing list ;)

[1]: https://github.com/instructlab/instructlab/releases
[2]: https://github.com/instructlab/instructlab/releases/tag/v0.15.0
[3]: https://github.com/instructlab#get-started-with-instructlab
[4]: https://github.com/instructlab/community/blob/main/Collaboration.md#email-lists

**Comment by lhawthorn** [comment]
> First off, why is this discussion in Issues and not in Discussions? I think not every passerby or community member check all the issues, but noticing something in Discussions might be.

@jimmysjolund Good question! We are using Issues for enhancements and Discussions for rapid updates on things like nasty bugs and up to the minute reporting for people not using Google Groups. This is documented [here](https://github.com/instructlab/community/blob/main/Collaboration.md#github-discussions) but maybe it could be improved. Plus I note I am talking about this in the issue tracker and not on the mailing list. I should at least add a pointer to this issue on list and will do that shortly.

> A blog is searchable in a better way than for instance a newsletter, I have many times tried find something and found what I needed in a blog post somewhere. I don't believe that will happen in another format. Blog posts will also be indexed by search engines, making it more accessible.

Good point, I hadn't even thought of the need for blogging vs. another medium for SEO reasons. 

> I also believe a blog might make it easier to get external people contributing, it's easier to write a blog post than to engage and get something included into a newsletter.

True that, plus if someone has written something useful elsewhere, asking if we might republish on our own blog is probably higher value to them than just being included in a list of links in a newsletter. Different people may feel differently about that idea, though.

> The backlog of potential topics is hard. What we have used in other communities is an editorial project on GitHub with a board showing Ideas, In writing, Published, etc. We just need to make sure the backlog of Ideas are filling up and is picked up into writing.

Like the editorial project board idea!

> If the newsletter could also be posted to the blog that would be ideal in my world:)

What if we included links to the blog posts in newsletters when we have enough content to feed a both? I feel confident we'd publish links to posts on the blog on announce list at least while the project is young.



> I'd expect release notes for this, and [we're doing that already](https://github.com/instructlab/instructlab/releases). Although maybe there's room to add a top-level paragraph picking out some highlights? 

+1 to blog posts that highlight info in release notes 
 
> > ... ways to contribute...
> 
> This also seems like something [we already do](https://github.com/instructlab#get-started-with-instructlab), and it's harder to fit into a periodic-release blog/newsletter publication cycle. Unless there are calendar events like irregular meetups/conferences that need to be pushed out to the community, and we may not be that far along yet?

Surprisingly enough, we are already getting there. We have two talks at conferences on InstructLab coming up in the next 30 days, which reminds me that they should get on the community calendar. Except I believe that @cybette is already on it.... (IBM Think keynote, which is livestreamed, and LF AI.Dev EU, where she is speaking! :)

> > ... in my ideal universe - news the project maintainers find interesting from the world of all things open and AI.
> 
> This kind of thing seems like a better fit for a newsletter/blog/periodic. If folks have a win like "wow, I used this tooling to build `$COOL_THING`, and here's a summary and link to _my_ blog about it...", that would be very interesting. But we already have [a users list](https://github.com/instructlab/community/blob/main/Collaboration.md#email-lists) that includes "user feedback on project", so not sure we need something flashier than that mailing list until we get at least one message to the mailing list ;)

I will admit I was also using this as part of my desire to fangirl some of the brightest minds in AI by inviting them to be interviewed about their points of view on open AI and also InstructLab. My ambitions are well and truly outed now.

**Comment by spotz** [comment]
We actually post to the RDO blog for instance and then send it to the mailing list as well to get the most eyes on things and then post links to the blog on socials. I'm pretty sure their could be some automation in there but we're a small group and do things manually.

**Comment by jimmysjolund** [comment]
> > First off, why is this discussion in Issues and not in Discussions? I think not every passerby or community member check all the issues, but noticing something in Discussions might be.
> 
> @jimmysjolund Good question! We are using Issues for enhancements and Discussions for rapid updates on things like nasty bugs and up to the minute reporting for people not using Google Groups. This is documented [here](https://github.com/instructlab/community/blob/main/Collaboration.md#github-discussions) but maybe it could be improved. Plus I note I am talking about this in the issue tracker and not on the mailing list. I should at least add a pointer to this issue on list and will do that shortly.

As a non-developer, that seems backwards to me. I would normally look to Discussions for "discussions", some of those might end up as enhancements for the future in which case they should be issues (referring to the discussion). As Discussions are "permanent" using it for temporary bug squashing, I would have thought that would rather be a temporary Slack channel (or similar chat, fast moving discussion that is not intended to be kept for a long time). Again, not being a developer this might be the usual way to do it, but if/when we are trying to attract a broader community there might be misunderstandings.

**Comment by jjasghar** [comment]
If I had a magic wand I'd ask everyone to use the mailing lists for everything apart from "fast moving conversations." Email works across all devices and engages with people who need all ways for accessibility. 

I get why we have the other channels but I'm starting to worry we created too many places for discussions.

**Comment by lhawthorn** [comment]
We have had a request from some of the folks on the CLI team to have a "blog planet" type of communication vehicle so that our maintainers can do quick blog posts and have them syndicated to a central location. @mairin mentioned it is important to ensure such a vehicle would have headshots and naming of whomever contributed the post.

I am going to drop this issue in the community channel for folks to discuss further.

@jasonbrooks How difficult would it be to set up a blog (e.g. shared WP instance with individuals having logins) so we can make it easyish for project maintainers to do regular blog updates? 

And, yes, the community team is signing up for help with editorial review and collecting thoughts together so that whatever is posted is most awesome and free of :hankey: emojis etc.

**Comment by jasonbrooks** [comment]
> We have had a request from some of the folks on the CLI team to have a "blog planet" type of communication vehicle so that our maintainers can do quick blog posts and have them syndicated to a central location. @mairin mentioned it is important to ensure such a vehicle would have headshots and naming of whomever contributed the post.
> 
> I am going to drop this issue in the community channel for folks to discuss further.
> 
> @jasonbrooks How difficult would it be to set up a blog (e.g. shared WP instance with individuals having logins) so we can make it easyish for project maintainers to do regular blog updates?

Easy if we pick an existing theme, a bit harder w/ a custom theme, someone would need to create it. We could at least start w/ an existing theme.

**Comment by jasonbrooks** [comment]
> We have had a request from some of the folks on the CLI team to have a "blog planet" type of communication vehicle so that our maintainers can do quick blog posts and have them syndicated to a central location. @mairin mentioned it is important to ensure such a vehicle would have headshots and naming of whomever contributed the post.
> 

On the other hand, if you want it to be more like a planet, with posts drawn from individual blogs but vetted centrally, Duck came up with a solution like that for Ceph using github PRs for the vetting portion.

**Comment by jimmysjolund** [comment]
> > We have had a request from some of the folks on the CLI team to have a "blog planet" type of communication vehicle so that our maintainers can do quick blog posts and have them syndicated to a central location. @mairin mentioned it is important to ensure such a vehicle would have headshots and naming of whomever contributed the post.
> > 
> 
> On the other hand, if you want it to be more like a planet, with posts drawn from individual blogs but vetted centrally, Duck came up with a solution like that for Ceph using github PRs for the vetting portion.

I like that approach. That would make it possible and easy to get posts from other than maintainers too.

**Comment by mairin** [comment]
Could we potentially do a combo approach, 1+2 below?

1. for folks who dont want to maintain a blog... use an account on a wpengine. rss of all ppsts aggregated into

2. duck's solution - byo blog and aggregated?

**Comment by jimmysjolund** [comment]
> Could we potentially do a combo approach, 1+2 below?
> 
> 1. for folks who dont want to maintain a blog... use an account on a wpengine. rss of all ppsts aggregated into
> 2. duck's solution - byo blog and aggregated?

Would that potentially double the maintenace/admin required? Otherwise, great, why not both!
