### ISSUE TITLE
Add maximum line length enforcement to Markdown Linter

### ISSUE THREAD

**Issue by nathan-weinberg** [instructlab/community#268]
Linter itself is already implemented, just need to add this to the config. Not sure exactly which value we want to use in terms of maximum line length.

**Comment by russellb** [comment]
The value of this is that when paragraphs are all on one line, it makes text diffs harder to read. One character changed means the whole paragraph is replaced in a diff vs just the line that the change was on.

It doesn't have to be a super aggressive limit, but *something* -- maybe 120 characters or something like that.

**Comment by lhawthorn** [comment]
+1 on 120 characters

Who can make the update? Looking at you @nathan-weinberg for a nomination or a PR to do the needful. Thank you!
