### ISSUE TITLE
create truly groovy demo video with InstructLab only branding

### ISSUE THREAD

**Issue by lhawthorn** [instructlab/community#273]
@makelinux had the excellent suggestion to add the [InstructLab demo video](https://www.youtube.com/watch?v=pgK-70iLz_o) to the  [Community README file](https://github.com/instructlab/community/blob/main/README.md), as it is an excellent demo video.

It is also heavily Red Hat branded, and while Red Hat as a company is very proud of our project founder status, we also have no wish to imply a level of 'ownership' we make no claim to have. We want anyone who can contribute to InstructLab, regardless of employer, to step up and take a leadership role in this project.

Thus, it is important that we make a demo video that is neutrally branded with InstructLab for our [project YouTube channel](https://www.youtube.com/@InstructLab).

It would be good to do it real soon now.

Thank you to @makelinux for surfacing this clear need to bring further clarity to our project participants.

**Comment by lhawthorn** [comment]
There is an opportunity to produce such a video in early July when @cybette and I will visit Boston and spend some time with much of the maintainer team in person.

Question I am curious about - how fancy marketing polished do we want a demo video be? I am all about a well polished demo video but I wonder if it detracts from our authenticity. I think it does not and I am overthinking, but I also appreciate thinking such topics through.

We should also beg @jeremyeder for his demo script so we can recycle it for this effort.

**Comment by cybette** [comment]
Thanks to @gshipley, we now have a couple of amazing getting started with InstructLab videos on our youtube channel:
1. [InstructLab: From 0 to aligned model using Mac OS](https://www.youtube.com/watch?v=Jb5dh3Uzdbw)
2. [InstructLab: Using Windows with InstructLab with Nvidia CUDA support](https://www.youtube.com/watch?v=EvpXokBpu8M) 

First video has been verified by yours truly, getting my very first macbook 2 days ago and went from 0 to aligned model in a day.

We've also received feedback that the second video was very helpful 👍 

In addition, we have some excellent [streaming content](https://www.youtube.com/playlist?list=PLSRSFJxh1W2L3cCzPntXpeHLQx14MZZsO) by @jjasghar and @paulczar, which I plan to grab shorts from and post them.

With these great content in place, we can close this issue. Thanks everyone!
