### ISSUE TITLE
Discarded instruction(didn't match expected format)

### ISSUE THREAD

**Issue by ldimaggi** [instructlab/community#300]
Not sure if this is a user error - or a lack of error information in the generate log - hoping that someone can help with this. 

In attempting to add knowledge to the merlinite-7b-lab-Q4_K_M.gguf model:

With this wikipedia entry:
https://en.wikipedia.org/wiki/Norumbega_Tower

And this github repo:
https://en.wikipedia.org/wiki/Norumbega_Tower

And ilab generate output fragment:
`INFO 2024-05-30 10:12:16,709 generate_data.py:468 Selected taxonomy path knowledge->textbook->history->norumbega-tower
INFO 2024-05-30 10:12:52,881 generate_data.py:468 Selected taxonomy path knowledge->textbook->history->norumbega-tower
Q> What is the significance of the Norumbega Tower in terms of historical interpretation?
I> 
A> The tower has played a significant role in shaping Americans’ understanding and appreciation of Norse history and its impact on North America. Its construction and design reflect Horsford’s conviction that Norse explorers had settled in New England, although there is no physical evidence to support this claim. The addition of the tower to Norumbega Park, a recreational complex located across the river in Newton, Massachusetts, also influenced how Americans perceived Norse history and its influence on North America.`

I am seeing this error in the generate log - can anyone explain what the expected format should be? 

Thanks!

`2024-05-30T09:45:19 - Discarded instruction(didn't match expected format): "\nInstruction\nWhat evidence exists to support or refute Horsford's claim that there were Norse settlements anywhere in New England?\nOutput\nThere is no archaeological or other evidence to support Horsford's claim that there were Norse settlements anywhere in New England. This highlights the importance of critical thinking and skepticism when considering historical claims, especially those made without physical evidence.\n" `

**Comment by jjasghar** [comment]
This would work better on the users@instructlab.ai mailing list then this GitHub issue tracker. Would you mind reposting this question there please?
