### ISSUE TITLE
Contact individuals in taxonomy team membership update

### ISSUE THREAD

**Issue by russellb** [instructlab/community#314]
https://github.com/instructlab/community/pull/313

This PR made significant changes to the teams associated with the taxonomy repository due to lack of activity.

If we go by the book -- https://github.com/instructlab/community/blob/main/CONTRIBUTOR_ROLES.md#stepping-down-and-the-emeritus-process -- the main expectation here would be

> Maintainers will make reasonable efforts to contact the absent contributor.

I don't believe this contact has been made in all cases. I've filed this issue to track the follow-up here to ensure someone reaches out to all of these individuals to explain the change and give an opportunity for response about their expected ongoing availability for team participation.

Thanks!

**Comment by nathan-weinberg** [comment]
Is `Administrators` a documented type of team?

**Comment by russellb** [comment]
Assigned @jjasghar as he made the changes and said he'd take up this issue

**Comment by jjasghar** [comment]
Yep, it's on my todo list. :)

**Comment by russellb** [comment]
settled via https://github.com/instructlab/community/pull/326
