### ISSUE TITLE
Contributor Promotion: Dominik Kawka

### ISSUE THREAD

**Issue by dominikkawka** [instructlab/community#352]
**Which member are you nominating for a team change?**
Dominik Kawka

**Current active maintainers sponsoring this nomination for the promotion?**
@caradelia @cybette @jjasghar 

Hello, I'm Dominik Kawka, the new Community Architect to join the team. I started this role on August 1st. Since starting, I've been attending the community and CLI meetings, and I even had the privilege to host a [community meeting](https://www.youtube.com/watch?v=5OQDiAB1KS8)!

I graduated from college with a 1.1. in `BSc (Hons) in Software Systems Development` this year in May. For my final year project, I built an image classifier using TensorFlow, which would distinguish between different dog breeds, and users could upload photos to the model via website.

As such, I would like to request to become a __member__ for this repo.

**Comment by cybette** [comment]
I'm sponsoring @dominikkawka, and additionally recommending Dominik for **maintainer** of the community repo (there's no triager role in this repo), due to his role as an AI Community Architect which will include responsibilities such as hosting community meetings.

**Comment by nathan-weinberg** [comment]
Appreciate the following of the process on this! It has made me notice we don't seem to have any kind of guidance around how to conclude these nominations like we do for Maintainer teams? https://github.com/instructlab/community/blob/main/CONTRIBUTOR_ROLES.md#member

**Comment by nathan-weinberg** [comment]
Also while I am not a `Community Maintainer` I am a Maintainer on several other teams and would support @dominikkawka's nomination :smile:

**Comment by nathan-weinberg** [comment]
If y'all are interested feel free to use the same nomination template we have in the CLI repo: https://github.com/instructlab/instructlab/blob/main/.github/ISSUE_TEMPLATE/team_recommend.md

**Comment by bjhargrave** [comment]
> As such, I would like to request to become a **member** for this repo.


> I'm sponsoring @dominikkawka, and additionally recommending Dominik for **maintainer** of the community repo

Is this nomination for Member or Maintainer? Member seems appropriate while Maintainer seems a big stretch.

+1 for Member.
-1 for Maintainer.

**Comment by jjasghar** [comment]
@dominikkawka has been involved in the community and maintains an extremely positive engagement. I've added him as a maintainer for the work he is being assigned from Red Hat.

Congratulations!
