### ISSUE TITLE
These sources are not cited on the page

### ISSUE THREAD

**Issue by jpodivin** [instructlab/community#364]
https://github.com/instructlab/community/blob/980cd070fb4c58e795f201a1b0d25ba69fe8c2fc/docs/README.md?plain=1#L42-L46

**Comment by jjasghar** [comment]
I'm betting they are put here as examples. We should be moving this over to docs.instructlab.ai, so maybe we'll remove them then.

We are auditing everything with the build of docs.instructlab.ai.
