### ISSUE TITLE
DEFINE SECURITY POLICY

### ISSUE THREAD

**Issue by joesepi** [instructlab/community#39]
### Required
- [x] turn on private vulnerability reporting within Github
- [ ] update community/SECURITY.md to point to private vulnerability reporting
- [x] turn on secret scanning (required by IBM open sourcing policy)
- [ ] turn on dependabot for all repos (required by IBM open sourcing policy)

### Optional
- [ ] (optionally) Run Snyk for security scan, I think Redhat also run Snyk. We do not have license to run anything else in [github.com](http://github.com/)
- [ ] (Recommended) Badge/Certify with OpenSSF - industry standard for best practice and security. At the very minimum we should get a passing badge

**Comment by lhawthorn** [comment]
This is fixed and security reporting along with email address to report has been set up.

**Comment by caradelia** [comment]
Based on above- good to close issue @lhawthorn ?
