### ISSUE TITLE
merge right clarification

### ISSUE THREAD

**Issue by mikebrow** [instructlab/community#75]
currently https://github.com/instruct-lab/community/blob/main/CONTRIBUTING.md#merge-approval states:

A change requires LGTMs **from two of the maintainers** of each component affected

Given we have reviewers and maintainers.. this should probably be "from two reviewers and/or maintainers for each component affected."

Some OSS projects count a commit submitted by a maintainer of a component as already having that maintainer's LGTM. Some do not.

Some OSS projects allow a maintainer to merge his own commit once the LGTM requirements have been met. Some do not.

**Comment by russellb** [comment]
> @lhawthorn Def fine with it being closed, but curious if we want this info to also live in the `community` repo, or just in `enhancements` - @russellb do you know the best practice here?

My mental model right now is:

* community - outward-facing content (content for new people, how to get started, how to get engaged, community participation practices and policies ...)
* enhancements - inward-facing content (designs, technical policies)

I would consider this more in the "technical policies" territory, though there's significant grey area with the governance and contributor roles here. Maybe high-level overview here is fine, but detailed policies more in enhancements? There's no clear right/wrong.

Related - I posted a PR to remove the "reviewer" role from that doc. It's not used anywhere in practice at this time. https://github.com/instructlab/community/pull/171
