### ISSUE TITLE
Email addresses needed

### ISSUE THREAD

**Issue by jjasghar** [instructlab/community#89]
When we get "instructlab.io" email via @jeremyeder 

EDIT: updated email addresses to remove prefix -@joesepi

<b style="font-weight:normal;" id="docs-internal-guid-72bf561b-7fff-40fb-f22a-86901ea2595c"><div dir="ltr" style="margin-left:0pt;" align="left">
Mailing list | Purpose
-- | --
announce@instructlab.io | Where we announce releases or other important updates.
dev@instructlab.io | Developer discussions.
maintainers@instructlab.io | Do we need a list for maintainers?  Used for pypi?
users@instructlab.io | User discussions, e.g. “my first PR”.
security@instructlab.io | Security issues and announcements
pypi@instructlab.io | Publishing to pypi (if we decide to break it out per package process)
coc@instructlab.io | Code of conduct reporting or communication.

</div></b>

**Comment by lhawthorn** [comment]
We will also need coc-reporting that goes to just the Code of Conduct Committee members.

**Comment by lhawthorn** [comment]
Make sure to add email addresses to the project FAQ - marked with TODO in doc and with link to this issue https://github.com/instructlab/community/blob/main/FAQ.md

**Comment by joesepi** [comment]
@luke-inglis brought up a good question in today's triage call asking if there was a place people could give feedback on any aspect of the project. @jjasghar suggested the users@instructlab.io email address as a place for such feedback and comments.

**Comment by cybette** [comment]
> @jjasghar suggested the [users@instructlab.io](mailto:users@instructlab.io) email address as a place for such feedback and comments.

+1 for using `users` for feedback

also we need to change `.io` to `.ai` :)

**Comment by lhawthorn** [comment]
We are creating the project mailing lists right now via Google Workspace. Here is the list of mailing lists as I understand them today and their purposes. List addresses will be ListPrefix@instructlab.ai

Mailing list | who can join group | who can view posts | who can post to group | who can post as group | purpose
-- | -- | -- | -- | -- | --
announce | anyone | anyone | admins | admins | Where we announce releases and other project wide updates
dev | anyone | anyone | members | noone | developer discussions, both front and backend
maintainers | invite only | members | members | admins | maintainer only discussions, private & used extremely sparingly
users | anyone | anyone | members | noone | user feedback on project or help getting started, e.g. "my first PR"
security | invite only | members | anyone | admins | reporting alias for vulnerabilities 
pypi | invite only | members | members | admins | publishing to PyPI
coc | invite only | members | anyone | admins | code of conduct reporting and communication
website | invite only | members | anyone | admins | website administration and maintenance e.g. analytics

**Comment by lhawthorn** [comment]
@mscherer is going to create these mailing lists for us, please stay tuned ...

**Comment by lhawthorn** [comment]
I will work on updating the docs, thank you @mscherer

**Comment by lhawthorn** [comment]
These email addresses have been created and documented at https://github.com/instructlab/community/blob/main/Collaboration.md

Going now to update the reporting email addresses for e.g. security-reporting
