### ISSUE TITLE
Have weekly community meeting set up

### ISSUE THREAD

**Issue by joesepi** [instructlab/community#98]

**Comment by lhawthorn** [comment]
Time chosen for weekly all community meetings is at 14:00 UTC. Here is a [handy time zone conversion link](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=5&day=14&hour=14&min=0&sec=0&p1=37&p2=43&p3=101&p4=224&p5=213&p6=771&p7=248&p8=2) for folks!

Still needs to be set up on google calendar (sigh, real soon now) and [documented in community repo](https://github.com/instructlab/community/blob/main/Collaboration.md), but we have selected a time.

**Comment by cybette** [comment]
Community meetings set up and added to [project calendar](https://calendar.google.com/calendar/embed?src=c_23c2f092cd6d147c45a9d2b79f815232d6c3e550b56c3b49da24c4b5d2090e8f%40group.calendar.google.com).
